name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

jobs:

  deploy-project:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Download latest release asset
        id: download-release-asset
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*.zip"

      - name: Unzip latest release asset
        run: |
          unzip -d release build-${{ steps.download-release-asset.outputs.tag_name }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy asset to AWS s3
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive
          aws s3 cp release s3://${{ secrets.AWS_S3_BUCKET }} --recursive